config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "avatars#index"
  resources :avatars
  resources :battles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :first_players, :class_name => 'Battle', :foreign_key => 'player_one_id', dependent: :destroy
  has_many :second_players, :class_name => 'Battle', :foreign_key => 'player_two_id', dependent: :destroy
  validates :name, :photo, :lives, :attacks, presence: true
  validates :lives, :attacks, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :player_one, :class_name => 'Avatar'
  belongs_to :player_two, :class_name => 'Avatar'
  belongs_to :weapon_one, :class_name => 'Weapon'
  belongs_to :weapon_two, :class_name => 'Weapon'
  belongs_to :shield_one, :class_name => 'Shield'
  belongs_to :shield_two, :class_name => 'Shield'
end

app/models/shield.rb
class Shield < ApplicationRecord
  has_many :first_shields, :class_name => 'Battle', :foreign_key => 'shield_one_id', dependent: :destroy
  has_many :second_shields, :class_name => 'Battle', :foreign_key => 'shield_two_id', dependent: :destroy
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :first_weapons, :class_name => 'Battle', :foreign_key => 'weapon_one_id', dependent: :destroy
  has_many :second_weapons, :class_name => 'Battle', :foreign_key => 'weapon_two_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def index
    @avatars = Avatar.all
  end

  def show
    @avatar = Avatar.find(params[:id])
  end

  def new
    @avatar = Avatar.new
  end

  def create
    @avatar = Avatar.new(avatar_params)
    @avatar.victories = 0
    if @avatar.save
      redirect_to avatar_path(@avatar)
    else
      render :new
    end
  end

  def edit
    @avatar = Avatar.find(params[:id])
  end

  def update
    @avatar = Avatar.find(params[:id])
    @avatar.update(avatar_params)
    redirect_to avatars_path
  end

  def destroy
    @avatar = Avatar.find(params[:id])
    @avatar.destroy
    redirect_to avatars_path
  end


  private

  def avatar_params
    params.require(:avatar).permit(:name, :photo, :lives, :attacks)
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find(params[:id])
  end

  def new
    @battle = Battle.new
  end

  def create
    @battle = Battle.new(battle_params)

    if @battle.player_one.lives > @battle.player_two.lives
      @avatar = @battle.player_one
    elsif @battle.player_one.lives < @battle.player_two.lives
      @avatar = @battle.player_two
    elsif @battle.player_one.lives == @battle.player_two.lives && @battle.player_one.attacks > @battle.player_two.attacks
      @avatar = @battle.player_one
    elsif @battle.player_one.lives == @battle.player_two.lives && @battle.player_one.attacks < @battle.player_two.attacks
      @avatar = @battle.player_two
    end

    if @avatar
      @battle.winner = @avatar.name
      @avatar.victories += 1
      @avatar.save
    else
      @battle.winner = "none"
    end

    if @battle.save
      redirect_to battle_path(@battle)
    else
      render :new
    end

  end


  private

  def battle_params
    params.require(:battle).permit(:player_one_id, :player_two_id, :weapon_one_id, :weapon_two_id, :shield_one_id, :shield_two_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/avatars/edit.html.erb
<div class="container">
  <div class= 'title'>
    <h2>Edit avatar</h2>
  </div>

  <div class="avatar-form">
    <%= simple_form_for(@avatar) do |f| %>
      <%= f.input :name%>

      <%= f.input :photo%>
      <%= f.input :photo_cache, as: :hidden%>

      <%= f.input :lives%>

      <%= f.input :attacks%>

       <%= f.submit class: 'btn btn-primary'%>
    <% end %>
  </div>

  <div class="back">
    <%= link_to avatar_path(@avatar) do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatar
    <% end %>
  </div>

</div>

app/views/avatars/index.html.erb
<div class= 'container'>
  <div class= 'game-explanation'>
    <div class= 'title'>
      <h1>Captain's Game</h1>
    </div>
    <div class= 'welcome-text-container'>
      <div class= 'welcome-text'>
        <p>Welcome aboard, young sailors! <br>
        Here you can try Captain Contrat's new game. <br>
        You'll be able to create new avatars if you like, <br> and launch a fight between your favorite characters ! <br>
        Enjoy ! :)
        </p>
      </div>

     </div>

    <div class='btns-battle'>
    <%= link_to new_battle_path do %>
      <div class ="battle-button btn btn-primary">
        Launch a Battle !
      </div>
    <% end %>

    <%= link_to battles_path do %>
      <div class ="history-button btn btn-secondary">
        History of battles
      </div>
    <% end %>
    </div>



  </div>

  <div class= 'title'>
      <h2>All my avatars</h2>
    </div>

  <div class='avatars-container'>
    <div class="avatars-list">
      <div class="row avatars-row">
        <% @avatars.each do |avatar| %>
          <div class="col-sm-3">
            <%= link_to avatar_path(avatar) do %>
              <div class='captain-card'>
                <h2 class="name-card"><%= avatar.name %> </h2>
                <div class='avatar-img'>
                <%= cl_image_tag avatar.photo, height: 200, width: 200 %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <%= link_to new_avatar_path do %>
      <div class ="new-avatar-button btn btn-primary">
        Create new avatar
      </div>
    <% end %>
  </div>

<!--   <div class="avatars-container">
  <div class="row avatars-row">
    <#% @avatars.each do |avatar| %>
      <div class="card-wrapper col-sm-3">
        <div class="card avatar-card">

          <div class="card-title">
            <h5><#%= avatar.name %></h5>
          </div>

          <div class="card-img-wrapper">
            <#%= cl_image_tag avatar.photo, class: "card-img-top",  height: 200%>
          </div>

        </div>
      </div>
    <#% end %>
  </div> -->
<!-- </div> -->

app/views/avatars/new.html.erb
<div class="container">
  <div class= 'title'>
      <h2>Create a new avatar!</h2>
  </div>

  <div class="avatar-form">
    <%= simple_form_for @avatar do |f| %>

      <%= f.input :name%>

      <%= f.input :photo%>
      <%= f.input :photo_cache, as: :hidden%>

      <%= f.input :lives, collection: 1..5 %>

      <%= f.input :attacks, collection: 1..5%>

      <%= f.submit class: 'btn btn-primary'%>

    <% end %>
  </div>

  <div class="back">
    <%= link_to avatars_path do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatars
    <% end %>
  </div>
</div>

app/views/avatars/show.html.erb
<div class="container">
  <div class="title">
    <h2><%= @avatar.name %></h2>
  </div>

  <div class="avatar-container">
    <div class="information-content">

      <div class="avatar-img">
      <%= cl_image_tag @avatar.photo, height: 350, width: 320 %>
      </div>

      <div class="avatar-information">
        <p> Lives: <%= @avatar.lives %></p>
        <p> Attacks: <%= @avatar.attacks %></p>
        <p> Number of battles: <%= @avatar.first_players.count + @avatar.second_players.count %></p>
        <p> Victories: <%= @avatar.victories %> </p>

        <% if @avatar.victories == 0 || @avatar.first_players.count + @avatar.second_players.count == 0 %>
          <p>Success Rate: 0% </p>
        <% else %>
          <p> Success Rate: <%= (@avatar.victories / (@avatar.first_players.count + @avatar.second_players.count).to_f * 100).round(1) %>% </p>
        <% end %>

        <div class="avatar-action">

          <%= link_to edit_avatar_path do %>
            <i class="fas fa-pencil-alt"> Edit</i>
          <% end %>

          <%= link_to avatar_path, method: :delete do %>
          <i class="delete-logo fas fa-trash-alt"> Delete</i>
          <% end %>

        </div>
      </div>



    </div>

    <div class="create-new-avatar-btn">
      <%= link_to new_avatar_path do %>
        <div class ="new-avatar-button btn btn-primary">
          Create new avatar
        </div>
      <% end %>
    </div>

  </div>


  <div class="back">
    <%= link_to avatars_path do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatars
    <% end %>
  </div>




</div>

app/views/battles/index.html.erb
<div class="container">

  <div class="title">
    <h2>All Battles (<%= @battles.count %>)</h2>
  </div>

  <div class='battles-container'>
    <div class="battles-list">
      <div class="row battles-row">
        <% @battles.each do |battle| %>
          <div class="col-sm-4">
            <%= link_to battle_path(battle) do %>
              <div class="captain-card">
                <div class="winner">
                  <h5><%= battle.player_one.name + ' Vs ' + battle.player_two.name %></h5>
                  <p><%= 'The winner is ... ' + battle.winner.upcase  + ' !!'%> <p>
                </div>

                <div class="battle-card">
                  <div class="player-one">
                    <%= cl_image_tag battle.player_one.photo, height: 100, width: 100, class: 'player-photo'%>
                    <p class="battle-avatar-info"><%= 'Player One: ' %><p>
                    <p class="battle-avatar-info"><%= battle.shield_one.name + ' - ' + battle.weapon_one.name %></p>
                  </div>

                  <div class="player-two">
                    <%= cl_image_tag battle.player_two.photo, height: 100, width: 100, class: 'player-photo' %>
                    <p class="battle-avatar-info"><%= 'Player Two: ' %><p>
                    <p class="battle-avatar-info"><%= battle.shield_two.name + ' - ' + battle.weapon_two.name %></p>
                  </div>
                </div>

              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="back">
    <%= link_to avatars_path do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatars
    <% end %>
  </div>


</div>

app/views/battles/new.html.erb
<div class="new-battle-page container">
  <div class= "title title-battle">
    <h2>Launch a new battle</h2>
  </div>

  <div class="form-container">
    <div class= "input">
      <%= form_for @battle do |f| %>
        <div class="players-form form">

          <div class="player-one">
            <h3>Player One</h3>
            <div class="form-field">
              <%= f.label :player_one %>
              <br>
              <%= f.collection_select(:player_one_id , Avatar.all, :id, :name) %>
            </div>

            <br>
            <div class="form-field">
              <%= f.label :weapon_one %>
              <br>
              <%= f.collection_select(:weapon_one_id , Weapon.all, :id, :name) %>
            </div>

            <br>
            <div class="form-field">
              <%= f.label :shield_one %>
              <br>
              <%= f.collection_select(:shield_one_id , Shield.all, :id, :name) %>
            </div>
          </div>


          <div class="player-two">
            <h3>Player Two</h3>
            <div class="form-field">
              <%= f.label :player_two %>
              <br>
              <%= f.collection_select(:player_two_id , Avatar.all, :id, :name) %>
            </div>

            <br>
            <div class="form-field">
              <%= f.label :weapon_two %>
              <br>
              <%= f.collection_select(:weapon_two_id , Weapon.all, :id, :name) %>
            </div>

            <br>
            <div class="form-field">
              <%= f.label :shield_two %>
              <br>
              <%= f.collection_select(:shield_two_id , Shield.all, :id, :name) %>
            </div>
          </div>

          <%= f.submit class: 'create-battle-btn btn btn-primary'%>
          <br>
          <br>

        </div>
      <% end %>

    </div>
  </div>

  <div class="back">
    <%= link_to avatars_path do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatars
    <% end %>
  </div>

</div>

app/views/battles/show.html.erb
<div class="container">
  <div class="title">
    <h2><%= @battle.player_one.name + ' Vs ' + @battle.player_two.name %></h2>
    <h2><%= @battle.created_at.to_s.first(10) %></h2>
  </div>

  <div class="battle-container">
    <div class="battle captain-card">

      <div class="winner battle-title">
        <h5><%= @battle.player_one.name + ' Vs ' + @battle.player_two.name %></h5>
        <p class="winner-sentence"><%= 'The winner is ... ' + @battle.winner.upcase  + ' !!'%> <p>
      </div>

      <div class="battle-card">
        <div class="player-one">
          <p><%= 'Player One: ' %><p>
          <%= cl_image_tag @battle.player_one.photo, height: 250, width: 250%>
          <p class="battle-info"><%= @battle.shield_one.name + ' - ' + @battle.weapon_one.name %></p>
        </div>

        <div class="player-two">
          <p><%= 'Player Two: ' %><p>
          <%= cl_image_tag @battle.player_two.photo, height: 250, width: 250%>
          <p class="battle-info"><%= @battle.shield_two.name + ' - ' + @battle.weapon_two.name %></p>
        </div>
      </div>

      <%= link_to new_battle_path do %>
        <div class ="battle-button btn btn-primary">
          Launch a Battle !
        </div>
      <% end %>

    </div>
  </div>


  <br>
  <%= link_to "Back to Battles' History", battles_path %>
  <br>

  <div class="back">
    <%= link_to avatars_path do %>
      <i class="fas fa-chevron-left"></i>
            Back to avatars
    <% end %>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaptainChallenge1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/DaniaAf" target="_blank"><i class="fab fa-github"></i></a>

    <a href="https://www.linkedin.com/in/dania-aflak/" target="_blank"><i class="fab fa-linkedin"></i></a>

  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by Dania
  </div>
</div>